type EmailLead = {
  id: string;
  kind: string;
  name: string;
  email: string;
  company: string | null;
  country: string | null;
  payload: Record<string, string>;
  createdAt: string;
};

type EmailRuntimeConfig = {
  RESEND_API_KEY?: string;
  FORM_NOTIFICATION_EMAIL?: string;
  FORM_FROM_EMAIL?: string;
};

const defaultRecipient = "abdullahahmedqureshint@gmail.com";

const formDefinitions: Record<string, { title: string; subject: (lead: EmailLead) => string; fields: Array<[string, string]> }> = {
  sprint_application: {
    title: "New Yalla Sprint application",
    subject: (lead) => `[Yalla Sprint] New application — ${lead.company || lead.name}`,
    fields: [
      ["name", "Founder name"], ["email", "Work email"], ["phone", "Phone number"],
      ["company", "Company"], ["companyWebsite", "Website / product link"], ["country", "Primary market"],
      ["stage", "Business stage"], ["revenue", "Current monthly revenue"], ["business", "What the business does"],
      ["goal", "Required Sprint outcome"], ["blocker", "Biggest current blocker"],
      ["termsAccepted", "Programme terms accepted"], ["privacyAccepted", "Privacy consent"],
    ],
  },
  booking_request: {
    title: "New call request",
    subject: (lead) => `[Yalla Startup] Call request — ${lead.company || lead.name}`,
    fields: [
      ["name", "Name"], ["email", "Email"], ["company", "Company"],
      ["preferredDate", "Preferred date"], ["goal", "What they want to discuss"], ["privacyAccepted", "Privacy consent"],
    ],
  },
  resource_download: {
    title: "Founder Readiness Checklist lead",
    subject: (lead) => `[Yalla Startup] Checklist download — ${lead.name}`,
    fields: [["name", "Name"], ["email", "Email"], ["country", "Market"], ["privacyAccepted", "Privacy consent"]],
  },
};

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

function displayValue(value?: string) {
  if (!value) return "Not provided";
  if (value === "yes") return "Yes";
  return value;
}

function getRuntimeConfig(): EmailRuntimeConfig {
  const injected = (globalThis as typeof globalThis & { __YALLA_EMAIL_ENV?: EmailRuntimeConfig }).__YALLA_EMAIL_ENV;
  return {
    RESEND_API_KEY: injected?.RESEND_API_KEY || process.env.RESEND_API_KEY,
    FORM_NOTIFICATION_EMAIL: injected?.FORM_NOTIFICATION_EMAIL || process.env.FORM_NOTIFICATION_EMAIL,
    FORM_FROM_EMAIL: injected?.FORM_FROM_EMAIL || process.env.FORM_FROM_EMAIL,
  };
}

function buildEmail(lead: EmailLead) {
  const definition = formDefinitions[lead.kind];
  const rows = definition.fields.map(([key, label]) => {
    const value = displayValue(lead.payload[key]);
    return `<tr><td style="width:32%;padding:14px 16px;border-bottom:1px solid #e5dfd2;color:#667579;font:700 11px Arial,sans-serif;text-transform:uppercase;letter-spacing:.06em;vertical-align:top">${escapeHtml(label)}</td><td style="padding:14px 16px;border-bottom:1px solid #e5dfd2;color:#071b1f;font:500 14px/1.6 Arial,sans-serif;white-space:pre-wrap;word-break:break-word">${escapeHtml(value)}</td></tr>`;
  }).join("");

  const html = `<!doctype html><html><body style="margin:0;background:#071b1f;padding:32px 14px"><div style="max-width:720px;margin:0 auto;background:#f7f3e9;border-top:5px solid #d8ff3e"><div style="padding:30px 32px;background:#0e2b2f;color:#fffdf8"><div style="color:#d8ff3e;font:800 10px Arial,sans-serif;letter-spacing:.18em;text-transform:uppercase">Yalla Startup · Venture Studio</div><h1 style="margin:18px 0 8px;font:400 32px/1.05 Georgia,serif">${escapeHtml(definition.title)}</h1><p style="margin:0;color:#b9c2c3;font:500 13px Arial,sans-serif">Submitted ${escapeHtml(new Date(lead.createdAt).toUTCString())}</p></div><div style="padding:18px 16px 8px"><table role="presentation" style="width:100%;border-collapse:collapse;background:#fffdf8;border:1px solid #e5dfd2">${rows}</table><div style="margin:18px 0;padding:16px;background:#eaff8d;color:#071b1f;font:600 12px/1.6 Arial,sans-serif"><strong>Submission ID:</strong> ${escapeHtml(lead.id)}<br><strong>Reply directly to:</strong> ${escapeHtml(lead.email)}</div></div><div style="padding:18px 32px 28px;color:#667579;font:500 11px/1.6 Arial,sans-serif">This notification was generated by the Yalla Startup website. The form submission remains saved even if email delivery is delayed.</div></div></body></html>`;
  const textRows = definition.fields.map(([key, label]) => `${label}: ${displayValue(lead.payload[key])}`).join("\n\n");
  const text = `${definition.title}\n\n${textRows}\n\nSubmission ID: ${lead.id}\nSubmitted: ${lead.createdAt}`;

  return { subject: definition.subject(lead), html, text };
}

export async function sendLeadNotification(lead: EmailLead): Promise<boolean> {
  const config = getRuntimeConfig();
  if (!config.RESEND_API_KEY) return false;

  const email = buildEmail(lead);
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      authorization: `Bearer ${config.RESEND_API_KEY}`,
      "content-type": "application/json",
      "idempotency-key": `lead-${lead.id}`,
    },
    body: JSON.stringify({
      from: config.FORM_FROM_EMAIL || "Yalla Startup <onboarding@resend.dev>",
      to: [config.FORM_NOTIFICATION_EMAIL || defaultRecipient],
      reply_to: lead.email,
      subject: email.subject,
      html: email.html,
      text: email.text,
      tags: [{ name: "form_kind", value: lead.kind }],
    }),
  });

  if (!response.ok) throw new Error(`Email provider returned ${response.status}`);
  return true;
}
